name: Hello CI 

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:                       
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout repo 
        uses: actions/checkout@v3

      - name: Set execute bit
        run: chmod +x hello.sh

      - name: Run Hello script 
        run: ./hello.sh
