name: Hello CI             # ワークフロー表示名

on:
  push:
    branches:
      - main               # main ブランチへの push で起動
  pull_request:            # PR の作成・更新でも起動

jobs:
  build:
    name: Run Hello script # ジョブ表示名
    runs-on: ubuntu-latest # Ubuntu 最新版 VM

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Ensure execute permission
        run: chmod +x hello.sh

      - name: Execute Hello script
        run: ./hello.sh
